### ISSUE TITLE
Mode PZEM in one bus

### ISSUE THREAD

**Issue by CreasolTech** [mce35/Domoticz-PZEM-004T#1]
I'm just trying your Domoticz plugin with PZEM-016.
It works great!
I had only a problem with the python3-pymodbus library installed with apt-get (raspbian): I had to 
```
apt purge python3-pymodbus
pip3 install python3-pymodbus
```
If you are still involved in this project, I suggest you to add a slave parameter where it's possible to specify one or more slave addresses:
_slave: 1,2,3,4,12,15_
for example to have 6 PZEM devices connected to the same bus .
Unit 1-4 associated to the first PZEM device, 9-12 to the second, 17-20 to the third, ....
Please let me know you think about.
Thanks for now for the good plugin.
Paolo

**Comment by mce35** [comment]
I am using pymodbus through pip as well, version 3.2.2, the version in raspbian is too old.

Having multiple PZEM connected to the same bus is in the TODO list but I didn't get time to look at it.

If you have some time to implement it, any PR is welcome :)

**Comment by mce35** [comment]
Hello @CreasolTech If you are still using this plugin, I added the possibility to read multiple meters on the same bus.

I didn't test it as I have only 1 meter connected.

After updating the plugin you should have a new parameter in domoticz:

![image](https://github.com/mce35/Domoticz-PZEM-004T/assets/3027018/f077b9af-ef90-4056-a197-c373a21fe0dc)

Let me know if it works!

**Comment by CreasolTech** [comment]
Thanks @mce35 .
I'm really sorry I did not informed you that I already wrote a plugin doing that: 
https://github.com/CreasolTech/domoticz-pzem-016
I also have a single PZEM module, so I didn't test more than one plugin at the same bus ;-) , but I've tested different types of devices working at the same bus by using different plugins (sometimes conflicting each-other) and it works quite good.
